// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/mattn/entgo-openapi-echo/ent/entry"
	"github.com/mattn/entgo-openapi-echo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	entryFields := schema.Entry{}.Fields()
	_ = entryFields
	// entryDescCreatedAt is the schema descriptor for created_at field.
	entryDescCreatedAt := entryFields[1].Descriptor()
	// entry.DefaultCreatedAt holds the default value on creation for the created_at field.
	entry.DefaultCreatedAt = entryDescCreatedAt.Default.(func() time.Time)
}
